# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_cuda_compiler_version10.0numpy1.17python3.6.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version10.0numpy1.17python3.6.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:10.0
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version10.0n_hba910a97ed
      linux_64_cuda_compiler_version10.0numpy1.17python3.7.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version10.0numpy1.17python3.7.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:10.0
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version10.0n_h22c7db7fe8
      linux_64_cuda_compiler_version10.0numpy1.17python3.8.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version10.0numpy1.17python3.8.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:10.0
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version10.0n_h87370301fc
      linux_64_cuda_compiler_version10.0numpy1.19python3.7.____73_pypypython_implpypy:
        CONFIG: linux_64_cuda_compiler_version10.0numpy1.19python3.7.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:10.0
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version10.0n_h474cc60b0f
      linux_64_cuda_compiler_version10.0numpy1.19python3.9.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version10.0numpy1.19python3.9.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:10.0
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version10.0n_hd76f759f8d
      linux_64_cuda_compiler_version10.1numpy1.17python3.6.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version10.1numpy1.17python3.6.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:10.1
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version10.1n_hcac15370b9
      linux_64_cuda_compiler_version10.1numpy1.17python3.7.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version10.1numpy1.17python3.7.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:10.1
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version10.1n_hf347f0c7c7
      linux_64_cuda_compiler_version10.1numpy1.17python3.8.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version10.1numpy1.17python3.8.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:10.1
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version10.1n_haf0bf580a9
      linux_64_cuda_compiler_version10.1numpy1.19python3.7.____73_pypypython_implpypy:
        CONFIG: linux_64_cuda_compiler_version10.1numpy1.19python3.7.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:10.1
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version10.1n_h1479de105e
      linux_64_cuda_compiler_version10.1numpy1.19python3.9.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version10.1numpy1.19python3.9.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:10.1
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version10.1n_h37f595f544
      linux_64_cuda_compiler_version10.2numpy1.17python3.6.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version10.2numpy1.17python3.6.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:10.2
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version10.2n_hf9d83061b0
      linux_64_cuda_compiler_version10.2numpy1.17python3.7.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version10.2numpy1.17python3.7.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:10.2
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version10.2n_hc905fe8add
      linux_64_cuda_compiler_version10.2numpy1.17python3.8.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version10.2numpy1.17python3.8.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:10.2
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version10.2n_hb1f4080dc8
      linux_64_cuda_compiler_version10.2numpy1.19python3.7.____73_pypypython_implpypy:
        CONFIG: linux_64_cuda_compiler_version10.2numpy1.19python3.7.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:10.2
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version10.2n_h8a0b1a4a19
      linux_64_cuda_compiler_version10.2numpy1.19python3.9.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version10.2numpy1.19python3.9.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:10.2
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version10.2n_h5076c40386
      linux_64_cuda_compiler_version11.0numpy1.17python3.6.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version11.0numpy1.17python3.6.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.0
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version11.0n_haac92fc00a
      linux_64_cuda_compiler_version11.0numpy1.17python3.7.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version11.0numpy1.17python3.7.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.0
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version11.0n_h2acfa02c1e
      linux_64_cuda_compiler_version11.0numpy1.17python3.8.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version11.0numpy1.17python3.8.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.0
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version11.0n_h9dfaf5f4c1
      linux_64_cuda_compiler_version11.0numpy1.19python3.7.____73_pypypython_implpypy:
        CONFIG: linux_64_cuda_compiler_version11.0numpy1.19python3.7.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.0
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version11.0n_hbec41b6621
      linux_64_cuda_compiler_version11.0numpy1.19python3.9.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version11.0numpy1.19python3.9.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.0
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version11.0n_h2e3ed3e479
      linux_64_cuda_compiler_version11.1numpy1.17python3.6.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version11.1numpy1.17python3.6.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.1
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version11.1n_h4dd4629884
      linux_64_cuda_compiler_version11.1numpy1.17python3.7.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version11.1numpy1.17python3.7.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.1
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version11.1n_h1b8c892860
      linux_64_cuda_compiler_version11.1numpy1.17python3.8.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version11.1numpy1.17python3.8.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.1
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version11.1n_h06efc350ca
      linux_64_cuda_compiler_version11.1numpy1.19python3.7.____73_pypypython_implpypy:
        CONFIG: linux_64_cuda_compiler_version11.1numpy1.19python3.7.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.1
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version11.1n_h37b23e37fd
      linux_64_cuda_compiler_version11.1numpy1.19python3.9.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version11.1numpy1.19python3.9.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.1
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version11.1n_hd30a5ef343
      linux_64_cuda_compiler_version11.2numpy1.17python3.6.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version11.2numpy1.17python3.6.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.2
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version11.2n_h1a6a7963d9
      linux_64_cuda_compiler_version11.2numpy1.17python3.7.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version11.2numpy1.17python3.7.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.2
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version11.2n_h1543737efd
      linux_64_cuda_compiler_version11.2numpy1.17python3.8.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version11.2numpy1.17python3.8.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.2
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version11.2n_h0a76830618
      linux_64_cuda_compiler_version11.2numpy1.19python3.7.____73_pypypython_implpypy:
        CONFIG: linux_64_cuda_compiler_version11.2numpy1.19python3.7.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.2
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version11.2n_he21b2c0e10
      linux_64_cuda_compiler_version11.2numpy1.19python3.9.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version11.2numpy1.19python3.9.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.2
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version11.2n_h097cd3888d
      linux_64_cuda_compiler_version9.2numpy1.17python3.6.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version9.2numpy1.17python3.6.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:9.2
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version9.2nu_hd38fea838f
      linux_64_cuda_compiler_version9.2numpy1.17python3.7.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version9.2numpy1.17python3.7.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:9.2
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version9.2nu_h3c5e31184e
      linux_64_cuda_compiler_version9.2numpy1.17python3.8.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version9.2numpy1.17python3.8.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:9.2
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version9.2nu_hd0bdb0b13e
      linux_64_cuda_compiler_version9.2numpy1.19python3.7.____73_pypypython_implpypy:
        CONFIG: linux_64_cuda_compiler_version9.2numpy1.19python3.7.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:9.2
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version9.2nu_hcf08b00c83
      linux_64_cuda_compiler_version9.2numpy1.19python3.9.____cpythonpython_implcpython:
        CONFIG: linux_64_cuda_compiler_version9.2numpy1.19python3.9.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:9.2
        SHORT_CONFIG_NAME: linux_64_cuda_compiler_version9.2nu_hdd0787205b
      linux_ppc64le_cuda_compiler_version10.2numpy1.17python3.6.____cpythonpython_implcpython:
        CONFIG: linux_ppc64le_cuda_compiler_version10.2numpy1.17python3.6.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le-cuda:10.2
        SHORT_CONFIG_NAME: linux_ppc64le_cuda_compiler_version_hba3755d816
      linux_ppc64le_cuda_compiler_version10.2numpy1.17python3.7.____cpythonpython_implcpython:
        CONFIG: linux_ppc64le_cuda_compiler_version10.2numpy1.17python3.7.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le-cuda:10.2
        SHORT_CONFIG_NAME: linux_ppc64le_cuda_compiler_version_h6acd32c6e8
      linux_ppc64le_cuda_compiler_version10.2numpy1.17python3.8.____cpythonpython_implcpython:
        CONFIG: linux_ppc64le_cuda_compiler_version10.2numpy1.17python3.8.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le-cuda:10.2
        SHORT_CONFIG_NAME: linux_ppc64le_cuda_compiler_version_haf764115b0
      linux_ppc64le_cuda_compiler_version10.2numpy1.19python3.7.____73_pypypython_implpypy:
        CONFIG: linux_ppc64le_cuda_compiler_version10.2numpy1.19python3.7.____73_pypypython_implpypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le-cuda:10.2
        SHORT_CONFIG_NAME: linux_ppc64le_cuda_compiler_version_hc2d7948484
      linux_ppc64le_cuda_compiler_version10.2numpy1.19python3.9.____cpythonpython_implcpython:
        CONFIG: linux_ppc64le_cuda_compiler_version10.2numpy1.19python3.9.____cpythonpython_implcpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le-cuda:10.2
        SHORT_CONFIG_NAME: linux_ppc64le_cuda_compiler_version_h590e5382ff
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
  - script: |
        artifact_name="conda_artifacts_$(build.BuildId)_$(SHORT_CONFIG_NAME)"
        echo "##vso[task.setVariable variable=ARTIFACT_NAME]$artifact_name"
        if [ -d build_artifacts ]; then
          echo "##vso[task.setVariable variable=CONDA_BLD_DIR_EXISTS]true"
        fi
    displayName: Check for conda build artifacts
    condition: succeededOrFailed()

  - publish: build_artifacts/
    artifact: $(ARTIFACT_NAME)
    condition: eq(variables.CONDA_BLD_DIR_EXISTS, 'true')